# Introduction to Numpy

In [2]:
import numpy as np

## Datatype and attributes

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
#Numpy's main datatype is ndarray 
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.5],[2,3,5.5]])
a2

array([[1. , 2. , 3.5],
       [2. , 3. , 5.5]])

In [6]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a4  = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](numpy_array_t.png)

In [8]:
a1.shape

(5,)

In [9]:
a2.shape #axis= 1 ,2

(2, 3)

In [10]:
a4.shape #axis = 0, 1,2

(2, 3, 3)

In [11]:
a3.shape

(3, 3)

In [12]:
a1.ndim,a2.ndim,a3.ndim,a4.ndim

(1, 2, 2, 3)

In [13]:
a1.dtype,a2.dtype,a3.dtype,a4.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [14]:
a1.size,a2.size,a3.size,a4.size

(5, 6, 9, 18)

In [15]:
type(a1),type(a2),type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
#Create panda's dataFrame from Numpy's array
import pandas as pd
df = pd.DataFrame(a2)

In [17]:
df

0    1    2
0  1.0  2.0  3.5
1  2.0  3.0  5.5

## Creating array 

In [18]:
sample_array =  np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(2,20,2) #(start,stop,step)
range_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
random_int = np.random.randint(0,10,size=(3,3))

In [37]:
random_int

array([[1, 6, 6],
       [1, 3, 3],
       [0, 4, 9]])

In [42]:
np.random.random((3,3))

array([[0.71569414, 0.94144521, 0.09090323],
       [0.0801931 , 0.40655173, 0.68504007],
       [0.65566913, 0.93389334, 0.82637752]])

In [46]:
np.random.rand(3,3)

array([[0.44681531, 0.17328786, 0.86314272],
       [0.37255849, 0.33527951, 0.79193525],
       [0.29776447, 0.01703332, 0.17232513]])

In [58]:
#pseudo-random number 
# np.random.seed(seed=0)
#lets run ran1 object multiple times snd see it will yeild diffrent output each time 
#what if someone else want to run my nteobook? they will get different output than I do
#and this is where power of seed comes in play 
ran1  = np.random.randint(10,size=(3,3))
ran1



array([[2, 7, 8],
       [2, 0, 5],
       [0, 2, 3]])

In [176]:
np.random.seed(seed=0)
ran2 = np.random.randint(10, size = (3,3))
ran2
#did you see? the random number generated onec are same everytime

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [177]:
#one value of seed is correspondence with 1 set of ran2 output
np.random.seed(seed=7)
ran2 = np.random.randint(10, size = (3,3))
ran2

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7]])

## Different ways of veiwing arrays and matrices 

In [178]:
#find unique numbers in an array 
np.unique(ran2)

array([3, 4, 6, 7, 9])

In [180]:
a1,a2,a3,a4

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3.5],
        [2. , 3. , 5.5]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [182]:
a1[0]

1

In [184]:
a4[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
a4[0][0][2]

3

In [195]:
a4[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [205]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[9, 0, 9, 5, 0],
         [2, 3, 5, 9, 0],
         [8, 0, 7, 0, 5],
         [7, 3, 1, 0, 2]],

        [[6, 1, 8, 1, 2],
         [2, 9, 7, 0, 4],
         [4, 0, 5, 4, 7],
         [1, 0, 7, 1, 5]],

        [[6, 8, 4, 0, 6],
         [9, 3, 2, 0, 1],
         [0, 8, 2, 7, 1],
         [9, 6, 9, 4, 6]]],


       [[[8, 1, 7, 9, 5],
         [8, 6, 1, 0, 7],
         [0, 7, 0, 3, 0],
         [4, 0, 8, 6, 2]],

        [[6, 2, 0, 1, 6],
         [4, 9, 4, 1, 7],
         [6, 2, 7, 0, 1],
         [7, 7, 2, 3, 0]],

        [[0, 5, 9, 9, 8],
         [0, 9, 1, 4, 0],
         [9, 3, 2, 3, 5],
         [2, 0, 8, 6, 6]]]])

In [207]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [210]:
#get the innermost vactor of a4 array 
a4[:,:,:,:4]

array([[[[9, 0, 9, 5],
         [2, 3, 5, 9],
         [8, 0, 7, 0],
         [7, 3, 1, 0]],

        [[6, 1, 8, 1],
         [2, 9, 7, 0],
         [4, 0, 5, 4],
         [1, 0, 7, 1]],

        [[6, 8, 4, 0],
         [9, 3, 2, 0],
         [0, 8, 2, 7],
         [9, 6, 9, 4]]],


       [[[8, 1, 7, 9],
         [8, 6, 1, 0],
         [0, 7, 0, 3],
         [4, 0, 8, 6]],

        [[6, 2, 0, 1],
         [4, 9, 4, 1],
         [6, 2, 7, 0],
         [7, 7, 2, 3]],

        [[0, 5, 9, 9],
         [0, 9, 1, 4],
         [9, 3, 2, 3],
         [2, 0, 8, 6]]]])

In [212]:
a4[:,:,:3,:4]

array([[[[9, 0, 9, 5],
         [2, 3, 5, 9],
         [8, 0, 7, 0]],

        [[6, 1, 8, 1],
         [2, 9, 7, 0],
         [4, 0, 5, 4]],

        [[6, 8, 4, 0],
         [9, 3, 2, 0],
         [0, 8, 2, 7]]],


       [[[8, 1, 7, 9],
         [8, 6, 1, 0],
         [0, 7, 0, 3]],

        [[6, 2, 0, 1],
         [4, 9, 4, 1],
         [6, 2, 7, 0]],

        [[0, 5, 9, 9],
         [0, 9, 1, 4],
         [9, 3, 2, 3]]]])

In [214]:
a4[:,:2,:3,:4]

array([[[[9, 0, 9, 5],
         [2, 3, 5, 9],
         [8, 0, 7, 0]],

        [[6, 1, 8, 1],
         [2, 9, 7, 0],
         [4, 0, 5, 4]]],


       [[[8, 1, 7, 9],
         [8, 6, 1, 0],
         [0, 7, 0, 3]],

        [[6, 2, 0, 1],
         [4, 9, 4, 1],
         [6, 2, 7, 0]]]])

In [216]:
a4[:1,:2,:3,:4]

array([[[[9, 0, 9, 5],
         [2, 3, 5, 9],
         [8, 0, 7, 0]],

        [[6, 1, 8, 1],
         [2, 9, 7, 0],
         [4, 0, 5, 4]]]])

## manipulating and comparing arrays

## Arithmetic`

In [218]:
c1 = np.array([1,2,3,4])

In [226]:
c2 = np.ones(4)

In [227]:
c1,c2

(array([1, 2, 3, 4]), array([1., 1., 1., 1.]))

In [228]:
c1+c2

array([2., 3., 4., 5.])

In [230]:
c1 - c2

array([0., 1., 2., 3.])

In [232]:
c1 * c2

array([1., 2., 3., 4.])

In [240]:
np.random.seed(0)
c3 = np.random.randint(10,size =(4,4))
c3

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]])

In [242]:
c1 * c3

array([[ 5,  0,  9, 12],
       [ 7, 18,  9, 20],
       [ 2,  8, 21, 24],
       [ 8, 16,  3, 24]])

In [243]:
#Array devision

In [245]:
c1/c2

array([1., 2., 3., 4.])

In [248]:
c3/c2

array([[5., 0., 3., 3.],
       [7., 9., 3., 5.],
       [2., 4., 7., 6.],
       [8., 8., 1., 6.]])

In [250]:
c3*5

array([[25,  0, 15, 15],
       [35, 45, 15, 25],
       [10, 20, 35, 30],
       [40, 40,  5, 30]])

In [252]:
np.square(c3)

array([[25,  0,  9,  9],
       [49, 81,  9, 25],
       [ 4, 16, 49, 36],
       [64, 64,  1, 36]])

In [254]:
np.add(c2,c3)

array([[ 6.,  1.,  4.,  4.],
       [ 8., 10.,  4.,  6.],
       [ 3.,  5.,  8.,  7.],
       [ 9.,  9.,  2.,  7.]])

In [257]:
c3%3

array([[2, 0, 0, 0],
       [1, 0, 0, 2],
       [2, 1, 1, 0],
       [2, 2, 1, 0]])

In [259]:
np.exp(c3)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01],
       [1.09663316e+03, 8.10308393e+03, 2.00855369e+01, 1.48413159e+02],
       [7.38905610e+00, 5.45981500e+01, 1.09663316e+03, 4.03428793e+02],
       [2.98095799e+03, 2.98095799e+03, 2.71828183e+00, 4.03428793e+02]])

In [261]:
np.log(c3)

<ipython-input-261-b1c13e623ecb>:1: RuntimeWarning: divide by zero encountered in log
  np.log(c3)


array([[1.60943791,       -inf, 1.09861229, 1.09861229],
       [1.94591015, 2.19722458, 1.09861229, 1.60943791],
       [0.69314718, 1.38629436, 1.94591015, 1.79175947],
       [2.07944154, 2.07944154, 0.        , 1.79175947]])