# Introduction to Numpy

In [2]:
import numpy as np

## Datatype and attributes

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [6]:
#Numpy's main datatype is ndarray 
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3.5],[2,3,5.5]])
a2

array([[1. , 2. , 3.5],
       [2. , 3. , 5.5]])

In [10]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])