# Introduction to Numpy

In [2]:
import numpy as np

## Datatype and attributes

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
#Numpy's main datatype is ndarray 
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.5],[2,3,5.5]])
a2

array([[1. , 2. , 3.5],
       [2. , 3. , 5.5]])

In [6]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a4  = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(5,)

In [11]:
a2.shape #axis= 1 ,2

(2, 3)

In [12]:
a4.shape #axis = 0, 1,2

(2, 3, 3)

In [13]:
a3.shape

(3, 3)

In [15]:
a1.ndim,a2.ndim,a3.ndim,a4.ndim

(1, 2, 2, 3)

In [18]:
a1.dtype,a2.dtype,a3.dtype,a4.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [19]:
a1.size,a2.size,a3.size,a4.size

(5, 6, 9, 18)

In [21]:
type(a1),type(a2),type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
#Create panda's dataFrame from Numpy's array
import pandas as pd
df = pd.DataFrame(a2)

In [23]:
df

0    1    2
0  1.0  2.0  3.5
1  2.0  3.0  5.5